name: Release
on:
  workflow_dispatch:
  push:
    tags:
      - '*'
jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - uses: actions/checkout@v2
      with:
        lfs: true
    - name: Checkout LFS objects
      run: |-
        git lfs install
        git lfs track "*.exe"
    - uses: ncipollo/release-action@v1
      with:
        artifacts: "driver/*.exe"
        token: ${{ secrets.GITHUB_TOKEN }}
