name: Release
on:
  workflow_dispatch:
  push:
    tags:
      - '*'
jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - name: Upload Release
      uses: ncipollo/release-action@v1
      with:
        artifacts: '/driver/*.exe'
        token: ${{ secrets.GITHUB_TOKEN }}
