name: Scrape latest data

on:
  workflow_dispatch:
  schedule:
    - cron:  '0 1 * * *'

env:
  GITHUB_TOKEN: ${{ secrets.PAT_AMD }}

jobs:
  scheduled:
    runs-on: ubuntu-latest
    steps:
    - name: Check out this repo
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
        token: ${{ secrets.PAT_AMD }}
    - name: Set up Python 3.9
      uses: actions/setup-python@v1
      with:
        python-version: 3.9
    - name: Install deps
      run: >-
          python -m pip install --upgrade pip &&
          pip install beautifulsoup4 && pip install requests && pip install markdownify
    - name: Check for AMD new versions
      run: |-
        echo "old_link=$(cat link.txt)" >> $GITHUB_ENV
        python clean.py > link.txt
        echo "link=$(cat link.txt)" >> $GITHUB_ENV        
    - name: create new tag based on link scraped
      if: env.link != env.old_link 
      run: |-
        echo "tag=${{ env.link }}" | grep -oP '(tag=)|(\d\d\.\d\d?\.\d\d?)' | tr -d "\n" >> $GITHUB_ENV
    - name: Extract version from latest tag on repo
      if: env.link != env.old_link 
      uses: damienaicheh/extract-version-from-tag-action@v1.0.0
    - name: Create lastest:tag
      if: env.link != env.old_link 
      run: echo "latest_tag=${{env.MAJOR}}.${{env.MINOR}}.${{env.PATCH}}" >> $GITHUB_ENV
    - name: Prepare link for curl
      if: env.link != env.old_link && env.tag != env.latest_tag
      run: |-
        echo "version=${{ env.link }}" | grep -oP '(version=)|(\d\d\.\d\d?\.\d\d?)' | tr -d "\n" | tr  "."  "-" >> $GITHUB_ENV   
    - name: Fetch link for full setup
      if: env.link != env.old_link && env.tag != env.latest_tag
      run: |-
        python clean_full.py ${{env.version}} > link_full.txt
        echo "link_full=$(cat link_full.txt)" >> $GITHUB_ENV
    - name: Save new full setup
      if: env.link != env.old_link && env.tag != env.latest_tag
      run:  |-
        curl --create-dirs -O --output-dir "driver" '${{ env.link_full }}' -K headers.txt --compressed
    - name: Generate new changelog
      if: env.link != env.old_link && env.tag != env.latest_tag
      run: |-
        python generate_changelog.py ${{env.version}} > generate_changelog.md
    - name: Create new Release 
      if: env.link != env.old_link && env.tag != env.latest_tag
      run: |-
        gh release create ${{ env.tag }} -t ${{ env.tag }} -F generate_changelog.md
        gh release upload ${{ env.tag }} ./driver/*.exe
    - name: Remove driver folder
      if: env.link != env.old_link && env.tag != env.latest_tag
      run: rm -rf ./driver    
    - name: Commit report
      if: env.link != env.old_link && env.tag != env.latest_tag
      run: |-
        git config user.name "Automated"
        git config user.email "actions@users.noreply.github.com"
        git add -A
        timestamp=$(date -u)
        git commit -m "Latest data: ${timestamp}" || exit 0
        git push origin main
  
